import func

if __name__ == '__main__':
    try:
        func.main()
    except Exception as e:
        print(f'Error: {e}')