import func

if __name__ == '__main__':
    try:
        func.table_of_multiplication()
    except Exception as e:
        print(f'Error: {e}')